### ISSUE TITLE
Not support Java 11 for exception javax.xml.bind.JAXBContext not present

### ISSUE THREAD

**Issue by yananhub** [xaecbd/RCT#4]
When I run the package of RCT-Analyze-2.0.0.jar in Java 11, I got an exception below
```
java.lang.TypeNotPresentException: Type javax.xml.bind.JAXBContext not present
        at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)
        at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95)
        at java.base/java.lang.Class.getGenericInterfaces(Class.java:1138)
```
The initial judgment is that the java.xml.bind module has been removed from Java 11, can you add it?

**Comment by TrumanDu** [comment]
[https://blog.csdn.net/szj9106/article/details/84589522?tdsourcetag=s_pcqq_aiomsg](https://blog.csdn.net/szj9106/article/details/84589522?tdsourcetag=s_pcqq_aiomsg)
